# Generated by Django 6.0.6 on 2026-06-17 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos_placar_exato', models.PositiveIntegerField(default=5)),
                ('pontos_resultado', models.PositiveIntegerField(default=3)),
                ('palpites_abertos', models.BooleanField(default=True)),
                ('criterio_desempate_1', models.CharField(choices=[('placares_exatos', 'Maior número de placares exatos'), ('acertos_resultado', 'Maior número de resultados corretos'), ('data_cadastro', 'Cadastro mais antigo')], max_length=30)),
                ('criterio_desempate_2', models.CharField(choices=[('placares_exatos', 'Maior número de placares exatos'), ('acertos_resultado', 'Maior número de resultados corretos'), ('data_cadastro', 'Cadastro mais antigo')], max_length=30)),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
        migrations.CreateModel(
            name='DiaJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
            ],
            options={
                'verbose_name': 'Dia Jogo',
                'verbose_name_plural': 'Dia Jogos',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45, unique=True)),
                ('sigla', models.CharField(max_length=3, unique=True)),
                ('bandeira', models.ImageField(upload_to='bandeiras/')),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Times',
            },
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('gols_casa', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gols_fora', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('encerrado', models.BooleanField(default=False)),
                ('dia_jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campeonato.diajogo')),
                ('time_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_como_casa', to='campeonato.time')),
                ('time_fora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_como_fora', to='campeonato.time')),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
            },
        ),
    ]
