# Generated by Django 6.0.6 on 2026-06-17 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campeonato', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Palpite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gols_casa', models.PositiveSmallIntegerField()),
                ('gols_fora', models.PositiveSmallIntegerField()),
                ('pontuacao', models.PositiveSmallIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateField(auto_now=True)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campeonato.jogo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Palpite',
                'verbose_name_plural': 'Palpites',
                'unique_together': {('usuario', 'jogo')},
            },
        ),
    ]
